name: "Publishing"

on:
  push:
    tags:
      - v*

jobs:
  analysis:
    uses: ziqq/flutter_ci_workflows/.github/workflows/analysis.yml@main

  package-publishing:
    needs: analysis
    uses: ziqq/flutter_ci_workflows/.github/workflows/publish_to_pub.yml@main
    with:
      PANA_TOTAL: '100'
    secrets:
      PUB_CREDENTIAL_JSON: ${{ secrets.PUB_CREDENTIAL_JSON }}
      PUB_OAUTH_ACCESS_TOKEN: ${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}
      PUB_OAUTH_REFRESH_TOKEN: ${{ secrets.PUB_OAUTH_REFRESH_TOKEN }}